#!/bin/bash
set -e
function process_files() {
    local dir_name="$1"
    local space_name="$2"
    ./rename -d "${dir_name}"
    ./organize -d "${dir_name}_r" -s "${space_name}"
    ./transform-nextjs-pages -d "${dir_name}_r_o"
    ./fix-headers "${dir_name}_r_o_t"
    ./fix-markdown "${dir_name}_r_o_t"
}

# To use the function:
process_files my_downloads/dcs dcs
process_files my_downloads/node node

