#!/bin/bash
mkdir -p app/dcs/api
echo '{"title": "API" }' > app/dcs/api/_meta.json
mkdir -p app/dcs/api/s3/credentials/
cat > app/dcs/api/s3/credentials/page.md << 'EOF'
---
title: S3 Credentials
---
EOF
mkdir -p app/dcs/api/s3/presigned-urls
cat > app/dcs/api/s3/presigned-urls/page.md << 'EOF'
---
title: Presigned URLs
---
EOF
mkdir -p app/dcs/api/s3/s3-compatility
cat > app/dcs/api/s3/s3-compatility/page.md << 'EOF'
---
title: S3 Compatibility
weight: 1
---
EOF
wget https://raw.githubusercontent.com/storj/gateway-st/58cbeebf1222b69517327bccccaa23d0e546e8be/docs/s3-compatibility.md -O - >> app/dcs/api/s3/s3-compatility/page.md
mv app/dcs/api-reference/uplink-cli app/dcs/api
mv app/dcs/immutability app/dcs/concepts/immutability
	#modified:   app/dcs/getting-started/page.md
mkdir -p app/dcs/getting-started
mv app/dcs/storage/considerations/page.md app/dcs/getting-started/page.md
rm -r app/dcs/storage
mkdir -p app/dcs/misc
mv app/dcs/backups app/dcs/misc
mv app/dcs/getting-started/gateway-mt app/dcs/misc
mv app/dcs/api-reference/linksharing-service app/dcs/misc
mv app/dcs/getting-started/quickstart-aws-sdk-and-hosted-gateway-mt app/dcs/misc
mv app/dcs/getting-started/quickstart-uplink-cli app/dcs/misc
mv app/dcs/api-reference/s3-compatible-gateway app/dcs/misc
mv app/dcs/api-reference/s3-gateway app/dcs/misc
mv app/dcs/solution-architectures app/dcs/misc
mv app/dcs/api-reference/storj-client-libraries app/dcs/misc
rm -r app/dcs/api-reference
mv app/dcs/support app/dcs/misc
mkdir -p app/dcs/installation
cat > app/dcs/installation/page.md << 'EOF'
---
title: Installation
weight: 1
---
How to install Storj
EOF
mv app/dcs/how-tos app/dcs/third-party-tools
mv app/dcs/filezilla app/dcs/third-party-tools
mv app/dcs/iconik-integration app/dcs/third-party-tools
mv app/dcs/mastodon app/dcs/third-party-tools
mv app/dcs/nextcloud-with-storj-dcs app/dcs/third-party-tools
mv app/dcs/pixelfed app/dcs/third-party-tools
mkdir -p app/dcs/web-console
echo '{"title": "Web Console" }' > app/dcs/web-console/_meta.json
mv app/dcs/billing-payment-and-accounts-1 app/dcs/web-console
mv app/dcs/billing app/dcs/web-console
mv app/dcs/dashboard app/dcs/web-console
mv app/dcs/projects app/dcs/web-console
mv app/dcs/getting-started/quickstart-objectbrowser app/dcs/web-console
mv app/dcs/getting-started/satellite-developer-account app/dcs/web-console
mv app/dcs/users app/dcs/web-console
