{
 "title": "Storage Nodes",
 "tags": [ "default" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Customer Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action=\"GET\"}[1d]))",
     "legendFormat": "Day"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action=\"GET\"}[1d])) * 30",
     "legendFormat": "Estimate Day"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action=\"GET\"}[1w]))",
     "legendFormat": "Week"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action=\"GET\"}[1w])) / 7 * 30",
     "legendFormat": "Estimate Week"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action=\"GET\"}[30d]))",
     "legendFormat": "Month"
    }
   ]
  },
  {
   "title": "Repair Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action!=\"GET\"}[1d]))",
     "legendFormat": "Day"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action!=\"GET\"}[1d])) * 30",
     "legendFormat": "Estimate Day"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action!=\"GET\"}[1w]))",
     "legendFormat": "Week"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action!=\"GET\"}[1w])) / 7 * 30",
     "legendFormat": "Estimate Week"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action!=\"GET\"}[30d]))",
     "legendFormat": "Month"
    }
   ]
  },
  {
   "title": "Growrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(used_space{field=\"recent\"}) - sum(used_space{field=\"recent\"} offset 1d)",
     "legendFormat": "Day"
    },
    {
     "expr": "(sum(used_space{field=\"recent\"}) - sum(used_space{field=\"recent\"} offset 1d)) * 30",
     "legendFormat": "Estimate Day"
    },
    {
     "expr": "sum(used_space{field=\"recent\"}) - sum(used_space{field=\"recent\"} offset 1w)",
     "legendFormat": "Week"
    },
    {
     "expr": "(sum(used_space{field=\"recent\"}) - sum(used_space{field=\"recent\"} offset 1w)) / 7 * 30",
     "legendFormat": "Estimate Week"
    },
    {
     "expr": "sum(used_space{field=\"recent\"}) - sum(used_space{field=\"recent\"} offset 30d)",
     "legendFormat": "Month"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(used_space{field=\"recent\"})",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum(((sgn(available_space{field=\"recent\"}) + 1) / 2) * available_space{field=\"recent\"})",
     "legendFormat": "Free Space"
    },
    {
     "expr": "sum(((sgn(available_space{field=\"recent\"}) + 1) / 2) * available_space{field=\"recent\"}) / ((sum(available_space{field=\"recent\"} offset 7d) - sum(available_space{field=\"recent\"})) / 7)",
     "legendFormat": "Time To Fill"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action=\"GET\"}[30d])) / sum(used_space{field=\"recent\"})",
     "legendFormat": "Customer Downloads"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\",action!=\"GET\"}[30d])) / sum(used_space{field=\"recent\"})",
     "legendFormat": "Repair Downloads"
    },
    {
     "expr": "sum(increase(download_success_byte_meter{field=\"total\"}[30d])) / sum(used_space{field=\"recent\"})",
     "legendFormat": "All Downloads"
    }
   ]
  },
  {
   "title": "Customer Downloads",
   "type": "timeseries",
   "description": "Downloaded bytes per hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(download_success_size_bytes{field=\"sum\",action=\"GET\"}[6m])",
     "legendFormat": "{{pod}} {{action}} downloads"
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "timeseries",
   "description": "Uploaded bytes per hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(upload_success_size_bytes{field=\"sum\"}[6m])",
     "legendFormat": "{{pod}} uploads"
    }
   ]
  },
  {
   "title": "Repair Downloads",
   "type": "timeseries",
   "description": "Downloaded bytes per hour",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(download_success_size_bytes{field=\"sum\",action=\"GET_REPAIR\"}[1h])",
     "legendFormat": "{{pod}} {{action}} downloads"
    }
   ]
  },
  {
   "title": "Score",
   "type": "timeseries",
   "description": "audit, suspension and online score",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "audit_reputation_score{field=\"recent\",satellite_id=\"_12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S\"} != 1",
     "legendFormat": "audit {{pod}}"
    },
    {
     "expr": "suspension_score{field=\"recent\",satellite_id=\"_12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S\"} != 1",
     "legendFormat": "suspension {{pod}}"
    },
    {
     "expr": "online_score{field=\"recent\",satellite_id=\"_12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S\"} != 1",
     "legendFormat": "online {{pod}}"
    }
   ]
  },
  {
   "title": "Alert: Audit Success Rate",
   "type": "timeseries",
   "description": "download sucess / download started over 30 minutes\n\nShould also detect timeouts (high amount of download started without success)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(download_success_count{field=\"value\", action=\"GET_AUDIT\"}[30m]) / increase(download_started_count{field=\"value\", action=\"GET_AUDIT\"}[30m])",
     "legendFormat": "{{pod}} {{action}}"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "used_space{field=\"recent\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alert: Download Success Rate",
   "type": "timeseries",
   "description": "download sucess / download started over 30 minutes\n\nShould also detect timeouts (high amount of download started without success)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(download_success_count{field=\"value\", action=\"GET\"}[6h]) / increase(download_started_count{field=\"value\", action=\"GET\"}[6h])",
     "legendFormat": "{{pod}} {{action}}"
    }
   ]
  },
  {
   "title": "GC Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "garbage_collection_loop_duration{field=\"recent\"}",
     "legendFormat": "{{pod}} GC"
    }
   ]
  },
  {
   "title": "Alert: Upload Success Rate",
   "type": "timeseries",
   "description": "download sucess / download started over 30 minutes\n\nShould also detect timeouts (high amount of download started without success)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(upload_success_count{field=\"value\"}[6h]) / increase(upload_started_count{field=\"value\"}[6h])",
     "legendFormat": "{{pod}} Upload"
    }
   ]
  },
  {
   "title": "GC Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "garbage_collection_pieces_deleted{field=\"recent\"}",
     "legendFormat": "{{pod}} GC"
    }
   ]
  },
  {
   "title": "Alert: Repair Success Rate",
   "type": "timeseries",
   "description": "download sucess / download started over 30 minutes\n\nShould also detect timeouts (high amount of download started without success)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(download_success_count{field=\"value\", action=\"GET_REPAIR\"}[6h]) / increase(download_started_count{field=\"value\", action=\"GET_REPAIR\"}[6h])",
     "legendFormat": "{{pod}} {{action}}"
    }
   ]
  },
  {
   "title": "Delete Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "piecedeleter_queue_size{field=\"recent\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alert: Checkin failure",
   "type": "timeseries",
   "description": "Detects any kind of network issue. The storage node should checkin once per hour.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "increase(function{name=\"__Service__pingSatelliteOnce\", field=\"failures\"}[61m])",
     "legendFormat": "{{pod}} checkin"
    }
   ]
  },
  {
   "title": "Alert: Order failure",
   "type": "timeseries",
   "description": "Detects any kind of network issue. The storage node should checkin once per hour.",
   "gridPos": { "h": 1, "w": 3, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "increase(function{name=\"__Service__SendOrders\", field=\"failures\"}[61m])",
     "legendFormat": "{{pod}} order failure"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 3, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "up{job=~\"storagenode.+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}